name: run_tests

on:
  push:
    branches: [master]
    paths:
      - .github/**
      - investpy/**
      - tests/**

jobs:
  run-investpy-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: [3.9, "3.10"]

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }} on ${{ matrix.os }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Upgrade pip and install requirements
      run: |
        python -m pip install --upgrade pip setuptools
        pip install poetry==1.2.0
        poetry config virtualenvs.create false
        poetry install --no-dev --no-root --no-interaction --with test
    
    - name: Run pytest tests
      run: pytest
